### ISSUE TITLE
Website causing SSL certification Error

### ISSUE THREAD

**Issue by FASTANDEXTREME** [JasjitBansia/NMMC-incompetence#1]
`Error occurred: HTTPSConnectionPool(host='nmmc.gov.in', port=443): Max retries exceeded with url: /navimumbai/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))`

Possible Solution: Make it parameter that check for ceritficate false

**Comment by JasjitBansia** [comment]
Fixed by disabling ssl verification on api request that pings the website for status
